### ISSUE TITLE
Sound settings are not persistent.

### ISSUE THREAD

**Issue by DhruvRajuPatel** [DhruvRajuPatel/TrippinOnTrivia#18]
We can disable sound, but once we load a new body via ajax, the navbar sound is reset and the icon is also reset.

**Comment by ttarlet2** [comment]
Idea: add a property to user that represents mute. Check for that property whenever you load a page.

**Comment by DhruvRajuPatel** [comment]
Added the property. Tad got it to be persistent.

**Comment by ttarlet2** [comment]
Icon works now, too
