### ISSUE TITLE
Leveling system

### ISSUE THREAD

**Issue by ttarlet2** [DhruvRajuPatel/TrippinOnTrivia#4]
We need to implement a leveling system for the accounts

**Comment by DhruvRajuPatel** [comment]
Specifics:

Each correctly answered question will give one experience point to the player, each level will have a scaled amount of experience needed to reach the subsequent level.
Difficulty of questions asked will scale to the player level. Players can increase up to level 20. 
Each level is separated by points, earn enough points, and you will level up. 
Players can also lose a point by missing five questions in a row, which will decrease their level if they lose enough points.

**Comment by DhruvRajuPatel** [comment]
Completed leveling system, need to make it scalable able to user level.
