### ISSUE TITLE
Powerups

### ISSUE THREAD

**Issue by ttarlet2** [DhruvRajuPatel/TrippinOnTrivia#6]
We need to code the logic behind powerups and give them to a User's player (and have them be removed when used)

**Comment by DhruvRajuPatel** [comment]
Specifics:

The ability to freeze the clock in game, for 30 seconds (Phone a Google).
The ability to eliminate two random answers to a question.
The ability to reroll a category if the randomly selected category is not wanted, the new category will be a random selection of the remaining five categories.

**Comment by DhruvRajuPatel** [comment]
Completed Phone a Google.
